### ISSUE TITLE
If you change teams right before map changes, you can't join.

### ISSUE THREAD

**Issue by Raptor007** [Raptor007/aq2-tng#28]
The code that prevents people from changing teams rapidly doesn't seem to reset its timer when the map changes.

**Comment by Raptor007** [comment]
Possibly related:  Sometimes when you change maps quickly, unjoined players can shoot their pistol while floating around, and may "die" when joining a team (team-change suicide).

**Comment by Raptor007** [comment]
Make sure `deadflag` gets set on all players when changing maps.

**Comment by Raptor007** [comment]
I _think_ this is because `client.resp` was not getting cleared at map change.

Possibly fixed here: https://github.com/Raptor007/aq2-tng/commit/598aa6a28eb0b7ae7098927f8435c68789e76d08

**Comment by Raptor007** [comment]
By clearing `client.resp` in g_spawn.c `SpawnEntities`, I might have broken `auto_join` in p_client.c `ClientBeginDeathmatch`.

It now keeps `client.resp.team` if `auto_join` is enabled: https://github.com/Raptor007/aq2-tng/commit/637c290972fd68b6176ed814bd145e905c9b48dd

**Comment by m4son** [comment]
After a map change I still cant join team with **bind x team 1**(2) for 5seconds
It works OK via menu.

**Comment by Raptor007** [comment]
@m4son  Are you using auto-balance?  I'm not sure if that's the reason but it could be related.

**Comment by m4son** [comment]
No, use_balancer is **"0"**

**Comment by Raptor007** [comment]
Thanks!  I think this should fix it: https://github.com/Raptor007/aq2-tng/commit/ca67a53480ae80009594c36006ecd22ec4672d1d

I'll push it to the main aq2-tng after I do a little more bug fixing and testing.

**Comment by Raptor007** [comment]
Pushed upstream!  Feel free to re-open this if you find problems again.
